site_name: SSU Coding Style Guide
repo_url: https://github.com/SSU-CS/style-guide

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
    - content.code.annotate 

nav:
    - Home: index.md
    # - Python Style Guide for SSU: python.md
    - SSU Style Guide for C/C++: cpp.md
    # - Makefile Style Guide for SSU: make.md
    - Tutorials: tutorials.md

markdown_extensions:
  # for buttons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # for admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # for code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # for content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # for annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences
